### ISSUE TITLE
Strike Risk of paths calculated and shown

### ISSUE THREAD

**Issue by Zach10a** [aliaksei135/seedpod_ground_risk#39]
I believe there used to be a feature that would allow the total population overflown by a path to be shown on the plot itself. Is this old code able to be used to show total strike risk for paths?

**Comment by aliaksei135** [comment]
The `TemporalPopulationEstimateLayer` still exists but is currently used only as input to the risk map layers. It is still exposed in the UI, but shouldn't be used for risk map creation as it only shows the population mapped out and does take into account crucial parts of the risk assessment process such as the UAS altitude and probabilistic analysis of its failure descent modes. The population layer is probably of more interest to geographers instead of UAS-oriented users.

The buffer was removed as it was only used as a stopgap prior to the current far more advanced analysis method.
